version: "3.8"
networks:
  farmacare:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - farmacare
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
  db:
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - farmacare
volumes:
  db-data:
    driver: local