basePath: /
definitions:
  dto.CreateDoctorRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      no_sip:
        type: string
      password:
        type: string
    required:
    - email
    - fullname
    - no_sip
    - password
    type: object
  dto.CreateDoctorResponse:
    properties:
      email:
        type: string
      fullname:
        type: string
      no_sip:
        type: string
      role:
        type: string
    type: object
  dto.CreateFeedbackRequest:
    properties:
      detail:
        type: string
      feedback_category_id:
        type: integer
      issue:
        type: string
    required:
    - detail
    - feedback_category_id
    - issue
    type: object
  dto.CreateFeedbackResponse:
    properties:
      detail:
        type: string
      feedback_category_id:
        type: integer
      issue:
        type: string
    required:
    - feedback_category_id
    type: object
  dto.CreatePharmacistRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      no_sipa:
        type: string
      password:
        type: string
    required:
    - email
    - fullname
    - no_sipa
    - password
    type: object
  dto.CreatePharmacistResponse:
    properties:
      email:
        type: string
      fullname:
        type: string
      no_sipa:
        type: string
      role:
        type: string
    type: object
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    required:
    - email
    - fullname
    - password
    type: object
  dto.CreateUserResponse:
    properties:
      email:
        type: string
      fullname:
        type: string
      role:
        type: string
    type: object
  dto.EditUserProfileRequest:
    properties:
      age:
        type: integer
      fullname:
        type: string
      height:
        type: number
      no_sip:
        type: string
      no_sipa:
        type: string
      password:
        type: string
      specialist:
        type: string
      title:
        type: string
      weight:
        type: number
    type: object
  dto.EditUserProfileResponse:
    properties:
      age:
        type: integer
      fullname:
        type: string
      height:
        type: number
      no_sip:
        type: string
      no_sipa:
        type: string
      specialist:
        type: string
      title:
        type: string
      weight:
        type: number
    type: object
  dto.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dto.GoogleLoginRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.ResetPasswordRequest:
    properties:
      password:
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
  dto.Status:
    properties:
      data: {}
      name:
        type: string
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API definition for FarmaCare Server
  title: FarmaCare Server
  version: "1.0"
paths:
  /auth/credential:
    get:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get user credential
      tags:
      - Auth
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: ForgotPasswordRequest
        in: body
        name: ForgotPasswordRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ForgotPasswordRequest'
      summary: Forgot password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: LoginRequest
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
      summary: Login user google
      tags:
      - Auth
  /auth/login-google:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: GoogleLoginRequest
        in: body
        name: GoogleLoginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.GoogleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
      summary: Login user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: CreateUserRequest
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateUserResponse'
      summary: Register new user
      tags:
      - Auth
  /auth/register/doctor:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: CreateDoctorRequest
        in: body
        name: CreateDoctorRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDoctorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateDoctorResponse'
      summary: Register new doctor
      tags:
      - Auth
  /auth/register/pharmacist:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: CreatePharmacistRequest
        in: body
        name: CreatePharmacistRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePharmacistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreatePharmacistResponse'
      summary: Register new pharmacist
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: ResetPasswordRequest
        in: body
        name: ResetPasswordRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResetPasswordRequest'
      summary: Reset password
      tags:
      - Auth
  /feedback/create:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: CreateFeedbackRequest
        in: body
        name: CreateFeedbackRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateFeedbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateFeedbackResponse'
      summary: Create feedback
      tags:
      - Feedback
  /healthcheck:
    get:
      consumes:
      - application/json
      description: Put all mandatory parameter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Status'
            type: array
      summary: Check system status
      tags:
      - Healthcheck
  /profile:
    get:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get user profile
      tags:
      - Profile
  /profile/edit:
    put:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: EditUserProfileRequest
        in: body
        name: EditUserProfileRequest
        required: true
        schema:
          $ref: '#/definitions/dto.EditUserProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.EditUserProfileResponse'
      summary: Edit user profile
      tags:
      - Profile
swagger: "2.0"
