# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: asclepius
  GCE_INSTANCE_ZONE: asia-southeast2-b


name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
  
      - name: Build
        run: go build
  
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  
      - name: Configure gcloud
        run: gcloud config set project ${{ env.PROJECT_ID }}
  
      - name: Copy binary to GCE instance
        run: gcloud compute scp ./myapp ${{ env.GCE_INSTANCE }}:~/myapp --zone ${{ env.GCE_INSTANCE_ZONE }}
  
      - name: SSH into GCE instance
        run: gcloud compute ssh ${{ env.GCE_INSTANCE }} --zone ${{ env.GCE_INSTANCE_ZONE }} --command "cd ~/myapp && ./myapp"
  
      - name: Deploy Complete
        uses: appleboy/ssh-action@master
      